#!/bin/bash
app=$YNH_APP_INSTANCE_NAME
notredirectports=(22000, 21027)

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Retrieve app settings
#path=$(sudo yunohost app setting $app path)
#domain=$(sudo yunohost app setting $app domain)
#username=$(sudo yunohost app setting $app user)
path=$(ynh_app_setting_get $app path)
domain=$(ynh_app_setting_get $app domain)
username=$(ynh_app_setting_get $app user)
containername=${path#/}_${username}

# Remove nginx configuration
sudo rm /etc/nginx/conf.d/${domain}.d/${containername}.conf

# Remove container
output=$(sudo python remove_container.py $app $containername)

#Close port with no redirection 
#notredirectport=$(echo $output | cut -f4 -d,)
if [ ! -f /.dockerinit ]; then
  for nrp in ${notredirectports[*]}
     do
        sudo yunohost firewall allow TCP $nrp
        sudo yunohost firewall allow UDP $nrp
  done
fi

#Remove config files
#sudo rm -rf /home/yunohost.docker/container-$app/config

# Reload
sudo service nginx reload
sudo yunohost app ssowatconf 
