#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Retrieve old app settings
#path=$(sudo yunohost app setting $app path)
#domain=$(sudo yunohost app setting $app domain)
#username=$(sudo yunohost app setting $app user)
path=$(ynh_app_setting_get $app path)
domain=$(ynh_app_setting_get $app domain)
username=$(ynh_app_setting_get $app user)
containername=${path#/}_${username}


# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

# Restore sources & data
output=$(sudo python restore_container.py $app $username $containername)
sudo cp -a ./sources /home/yunohost.docker/container-${app}/${username}


# Restore NGINX configuration
sudo cp -a ./nginx.conf /etc/nginx/conf.d/${domain}.d/${containername}.conf

# Restart webserver
sudo service nginx reload