#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

app=$YNH_APP_INSTANCE_NAME
allports=(8384, 22000, 21027)
support_multiuser=false

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
admin=$(ynh_app_setting_get "$app" admin)
is_public=$(ynh_app_setting_get "$app" is_public)
language=$(ynh_app_setting_get "$app" language)

# Remove trailing "/" for next commands
if $support_multiuser; then
        path=${path%/}
else
        echo "Add username to path"
        path=${path%/}_${username}
fi

containername=${path#/}_${username}

#Install or upgrade pip and docker-py
echo "Install or upgrade docker-py"
sudo pip install docker-py --upgrade

#Create Docker container via python script
echo "Upgrade container, please wait..."
output=$(sudo python upgrade_container.py $app $username $datapath $containername $allports $(hostname) $dockerized)

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo sed -i "s@USERNAME@$username@g" ../conf/nginx.conf
sudo sed -i "s@CONTAINERIP@$ip@g" ../conf/nginx.conf
sudo sed -i "s@PORT@$redirectport@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/${domain}.d/${containername}.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [[ $is_public -eq 1 ]];
then
  # See install script
  ynh_app_setting_set "$app" unprotected_uris "/"
fi


# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
